# This file was generated by GoReleaser. DO NOT EDIT.
cask "backbrief" do
  version "20260928-2"

  on_macos do
    on_arm do
      sha256 "9c14fc18274877c7b972f99208bbc0cb0c3118e4110b48d74220a43592f58c9b"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d15623326e15651a7a0522c1e27ac576d8200334aa8f6063df493896d86612eb"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d5d13df2bcb5a83dd1b7ac01c7db672d0ab841da2a64469edb7707e83825d4e"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb5c61ece9665525bd0468efb558d989ba4d44bdc2aeb21d75d36d7c3f781971"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_linux_amd64.tar.gz"
    end
  end

  name "backbrief"
  desc "Repository status board for the GRIDWATCH org"
  homepage "https://github.com/gridwatch/backbrief"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backbrief"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], must_succeed: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backbrief"], must_succeed: false
    end
  end

  # No zap stanza required
end
