# This file was generated by GoReleaser. DO NOT EDIT.
cask "backbrief" do
  version "20260925-1"

  on_macos do
    on_arm do
      sha256 "33a8cc2246e0a4e1ee374438a67c6d145bd7fda6197ae3589a7850f37da39957"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5696f72e33f22a7de836eb9d563e871849e4fc6def90879ef76020c7efea9c91"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c1f09bb7106c6f98d67e01c8ba19be16fab25dd922bf49d1778e09b4fdc7d1df"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5db13d46e12fbc7a5a821ae734dfcef99dbe7f2988038bf847523936f5b6a81"
      url "https://github.com/gridwatch/backbrief/releases/download/v#{version}/backbrief_#{version}_linux_amd64.tar.gz"
    end
  end

  name "backbrief"
  desc "Repository status board for the GRIDWATCH org"
  homepage "https://github.com/gridwatch/backbrief"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "backbrief"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"], must_succeed: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backbrief"], must_succeed: false
    end
  end

  # No zap stanza required
end
